# Generated by Django 3.1.3 on 2021-01-01 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('motivo_visita', models.CharField(blank=True, max_length=300)),
                ('fecha_visita', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=30)),
                ('edad', models.CharField(blank=True, max_length=100)),
                ('especie', models.CharField(blank=True, max_length=30)),
                ('raza', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('esterilizado', models.BooleanField(blank=True, default=False)),
                ('motivo_visita', models.CharField(blank=True, max_length=300)),
                ('recordar_cita', models.BooleanField(blank=True, default=False)),
                ('medio', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
