# Generated by Django 3.1.3 on 2021-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210101_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fecha_visita',
            field=models.DateField(auto_now_add=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, max_length=30),
        ),
    ]
