# Generated by Django 3.1.3 on 2021-01-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210101_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fecha_visita',
            field=models.DateField(blank=True, max_length=30),
        ),
    ]
