# Generated by Django 3.1.3 on 2021-01-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210101_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'macho'), ('hembra', 'hembra')], max_length=8),
        ),
    ]
