# Generated by Django 3.1.3 on 2021-01-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210105_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medio',
            field=models.CharField(blank=True, choices=[('Llamada', 'Llamada'), ('WhatsApp', 'WhatsApp'), ('Correo', 'Correo'), ('Facebook', 'Facebook')], max_length=15),
        ),
    ]
