FROM python:3
ENV PYTHONBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE 1
WORKDIR /vetapi
COPY requirements.txt /vetapi/
RUN apt-get update && apt-get install -y netcat
ENTRYPOINT ["/vetapi/entrypoint.sh"]
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /vetapi/