version: "3.9"
   
services:
  db:
    container_name: postgresql
    image: postgres:latest
    env_file: 
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/vetapi
    ports:
      - "8090:8090"
    depends_on:
      - db
volumes:
  postgres-data:

